---
name: pdns

releases:
- name: pdns
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: pdns
  instances: 1
  azs: [ z1 ]
  vm_type: default
  persistent_disk_type: default
  stemcell: ubuntu
  networks:
  - name: default
  jobs:
  - name: smoke-test
    release: pdns
    properties: {}
  - name: pdns
    release: pdns
    properties:
      sqlite:
        database: dns.db
      pdns_conf: |
        launch=gsqlite3
        gsqlite3-database=/var/vcap/store/pdns/dns.db
        do-ipv6-additional-processing=no
        local-address=0.0.0.0:53
        only-notify=0.0.0.0/0
        webserver=true
        webserver-address=0.0.0.0
        webserver-allow-from=0.0.0.0/0
        api=yes
        api-key=((api_key))

variables:
  - name: api_key
    type: password

update:
  canaries: 1
  max_in_flight: 10
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
