---
name: pdns

releases:
- name: pdns
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: pdns
  instances: 1
  azs: [ vsphere ]
  vm_type: small
  persistent_disk_type: default
  stemcell: ubuntu
  networks:
  - name: vsphere-guest
  jobs:
  - name: pdns
    release: pdns
    properties:
      pdns_conf: |
        launch=pipe
        pipe-command=/var/vcap/jobs/pdns/bin/pipe.example.com.pl
        local-ipv6=

update:
  canaries: 1
  max_in_flight: 10
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
