---
name: pdns

releases:
- name: pdns
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: pdns
  instances: 1
  azs: [ z1 ]
  vm_type: default
  persistent_disk_type: default
  stemcell: ubuntu
  networks:
  - name: default
  jobs:
  - name: smoke-test
    release: pdns
  - name: pdns
    release: pdns
    properties:
      pdns:
        api_key: ((api_key))

variables:
  - name: api_key
    type: password

update:
  canaries: 1
  max_in_flight: 10
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
