---
name: pdns

releases:
- name: pdns
  version: 1.0.3+dev.1

stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: pdns
  instances: 1
  azs: [ z1 ]
  vm_type: default
  persistent_disk_type: default
  stemcell: ubuntu
  networks:
  - name: default
  jobs:
  - name: smoke-test
    release: pdns
  - name: pdns
    release: pdns
    properties:
      pdns:
        api_key: ((api_key))
      zones:
        - name: example.com
          records:
            - name: example.com
              type: SOA
              content: localhost admin.example.com 1 10380 3600 604800 3600
              ttl: 86400
            - name: www.example.com
              type: A
              ttl: 500
              content: 10.0.0.1
            - name: www.example.com
              type: A
              ttl: 500
              content: 10.0.0.2

variables:
  - name: api_key
    type: password

update:
  canaries: 1
  max_in_flight: 10
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
